/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      colors: {
        'bg-base':     '#0e1117',
        'bg-surface':  '#161b22',
        'bg-panel':    '#0d1117',
        'bg-card':     '#161b22',
        'bg-elevated': '#1c2128',
        'neon-indigo': '#00d4aa',
        'neon-violet': '#00b894',
        'neon-cyan':   '#58a6ff',
        'neon-purple': '#a371f7',
        'neon-blue':   '#58a6ff',
        'terminal-ok':     '#00d4aa',
        'terminal-warn':   '#f0a500',
        'terminal-danger': '#ff4444',
        'terminal-info':   '#58a6ff',
        'terminal-gold':   '#f0a500',
        'text-primary':   '#e2e8f0',
        'text-secondary': '#c9d1d9',
        'text-muted':     '#8b949e',
        'text-dim':       '#6e7681',
      },
      boxShadow: {
        'neon-indigo':    '0 0 16px rgba(99,102,241,0.35)',
        'neon-indigo-lg': '0 0 32px rgba(99,102,241,0.45)',
        'neon-cyan':      '0 0 16px rgba(6,182,212,0.3)',
        'neon-ok':        '0 0 16px rgba(16,185,129,0.3)',
        'neon-ok-lg':     '0 0 32px rgba(16,185,129,0.45)',
        'neon-danger':    '0 0 16px rgba(239,68,68,0.3)',
      },
      animation: {
        'blink':      'blink 2s ease-in-out infinite',
        'float':      'float 4s ease-in-out infinite',
        'slide-in':   'slideIn 0.25s ease',
        'fade-up':    'fadeUp 0.3s ease forwards',
        'ticker':     'ticker 30s linear infinite',
        'shimmer':    'shimmer 1.5s infinite',
        'ring-1':     'spin 1.2s linear infinite',
        'ring-2':     'spinReverse 1.8s linear infinite',
        'ring-3':     'spin 2.4s linear infinite',
        'pulse-dot':  'pulseDot 1.5s ease-in-out infinite',
      },
      keyframes: {
        blink:       { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
        float:       { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-6px)' } },
        slideIn:     { from: { opacity: '0', transform: 'translateX(-5px)' }, to: { opacity: '1', transform: 'none' } },
        fadeUp:      { to: { opacity: '1' } },
        ticker:      { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        shimmer:     { to: { backgroundPosition: '-200% 0' } },
        spinReverse: { to: { transform: 'rotate(-360deg)' } },
        pulseDot:    { '0%, 100%': { boxShadow: '0 0 4px currentColor' }, '50%': { boxShadow: '0 0 8px currentColor' } },
      },
    },
  },
  plugins: [],
}
