import type { BacktestMatch } from './harness.js'

/** Synthetic but realistic timelines — odds/scores shaped like TxODDS packets. */
export const SAMPLE_MATCHES: BacktestMatch[] = [
  {
    matchId: '17588316',
    label: 'Germany vs Curacao',
    ticks: [
      {
        atMs: 0,
        signal: {
          id: 'txodds:17588316:open',
          sourceTag: 'txodds',
          sourceRef: '17588316:open',
          subjectType: 'match_event',
          label: 'Germany vs Curacao',
          type: 'odds_shift',
          value: 72,
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588316',
          teams: { home: 'Germany', away: 'Curacao' },
          market: '1X2 · Home',
          rawPayload: {
            stream: 'odds',
            FixtureId: 17588316,
            MessageId: 'open',
            Pct: ['72.000'],
            SuperOddsType: '1X2',
          },
        },
      },
      {
        atMs: 3_000,
        signal: {
          id: 'txodds:17588316:m1',
          sourceTag: 'txodds',
          sourceRef: '17588316:m1',
          subjectType: 'match_event',
          label: 'Germany vs Curacao',
          type: 'odds_shift',
          value: 74,
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588316',
          teams: { home: 'Germany', away: 'Curacao' },
          market: '1X2 · Home',
          rawPayload: {
            stream: 'odds',
            FixtureId: 17588316,
            MessageId: 'm1',
            Pct: ['74.000'],
            SuperOddsType: '1X2',
          },
        },
      },
      {
        atMs: 5_000,
        signal: {
          id: 'txodds:17588316:goal',
          sourceTag: 'txodds',
          sourceRef: '17588316:goal',
          subjectType: 'match_event',
          label: 'Germany vs Curacao',
          type: 'goal',
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588316',
          teams: { home: 'Germany', away: 'Curacao' },
          score: { home: 1, away: 0 },
          rawPayload: {
            stream: 'scores',
            fixtureId: 17588316,
            seq: 40,
            action: 'goal',
            dataSoccer: { Goal: true },
          },
        },
      },
      {
        atMs: 6_500,
        signal: {
          id: 'txodds:17588316:post',
          sourceTag: 'txodds',
          sourceRef: '17588316:post',
          subjectType: 'match_event',
          label: 'Germany vs Curacao',
          type: 'odds_shift',
          value: 78,
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588316',
          teams: { home: 'Germany', away: 'Curacao' },
          market: '1X2 · Home',
          rawPayload: {
            stream: 'odds',
            FixtureId: 17588316,
            MessageId: 'post',
            Pct: ['78.000'],
            SuperOddsType: '1X2',
          },
        },
      },
      {
        atMs: 90 * 60_000,
        signal: {
          id: 'txodds:17588316:ft',
          sourceTag: 'txodds',
          sourceRef: '17588316:ft',
          subjectType: 'match_event',
          label: 'Germany vs Curacao',
          type: 'full_time',
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588316',
          teams: { home: 'Germany', away: 'Curacao' },
          score: { home: 2, away: 0 },
          market: 'F',
          rawPayload: {
            stream: 'scores',
            fixtureId: 17588316,
            seq: 900,
            gameState: 'F',
            action: 'full_time',
          },
        },
      },
    ],
  },
  {
    matchId: '17588305',
    label: 'Netherlands vs Japan',
    ticks: [
      {
        atMs: 0,
        signal: {
          id: 'txodds:17588305:open',
          sourceTag: 'txodds',
          sourceRef: '17588305:open',
          subjectType: 'match_event',
          label: 'Netherlands vs Japan',
          type: 'odds_shift',
          value: 55,
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588305',
          teams: { home: 'Netherlands', away: 'Japan' },
          market: '1X2 · Home',
          rawPayload: {
            stream: 'odds',
            FixtureId: 17588305,
            MessageId: 'open',
            Pct: ['55.000'],
            SuperOddsType: '1X2',
          },
        },
      },
      {
        atMs: 2_000,
        signal: {
          id: 'txodds:17588305:vel',
          sourceTag: 'txodds',
          sourceRef: '17588305:vel',
          subjectType: 'match_event',
          label: 'Netherlands vs Japan',
          type: 'odds_shift',
          value: 68,
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588305',
          teams: { home: 'Netherlands', away: 'Japan' },
          market: '1X2 · Home',
          rawPayload: {
            stream: 'odds',
            FixtureId: 17588305,
            MessageId: 'vel',
            Pct: ['68.000'],
            SuperOddsType: '1X2',
          },
        },
      },
      {
        atMs: 4_000,
        signal: {
          id: 'txodds:17588305:red',
          sourceTag: 'txodds',
          sourceRef: '17588305:red',
          subjectType: 'match_event',
          label: 'Netherlands vs Japan',
          type: 'red_card',
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588305',
          teams: { home: 'Netherlands', away: 'Japan' },
          score: { home: 0, away: 0 },
          rawPayload: {
            stream: 'scores',
            fixtureId: 17588305,
            seq: 55,
            action: 'red_card',
            dataSoccer: { RedCard: true },
          },
        },
      },
      {
        atMs: 90 * 60_000,
        signal: {
          id: 'txodds:17588305:ft',
          sourceTag: 'txodds',
          sourceRef: '17588305:ft',
          subjectType: 'match_event',
          label: 'Netherlands vs Japan',
          type: 'full_time',
          msgTimestamp: '',
          ingestTimestamp: '',
          matchId: '17588305',
          teams: { home: 'Netherlands', away: 'Japan' },
          score: { home: 0, away: 1 },
          market: 'F',
          rawPayload: {
            stream: 'scores',
            fixtureId: 17588305,
            seq: 901,
            gameState: 'F',
            action: 'full_time',
          },
        },
      },
    ],
  },
]
