#!/usr/bin/env bash
# CryptoCheck signal publishers — droplet deploy script
#
# Run on the DigitalOcean droplet:
#   bash deploy/deploy.sh
#
# Prerequisites:
#   - Docker + compose plugin installed
#   - Repo cloned at /opt/cryptocheck
#   - TELEGRAM_SESSION_STRING generated locally: cd services/ingestion && npm run auth

set -euo pipefail

REPO_DIR="/opt/cryptocheck"
COMPOSE_PROJECT="cryptocheck-signal"
COMPOSE_FILE="deploy/docker-compose.signal.yml"
ENV_FILE="deploy/.env.signal"

# ── Setup ─────────────────────────────────────────────────────────────────────

echo "=== CryptoCheck signal publishers deploy ==="
echo ""

if [[ ! -d "$REPO_DIR" ]]; then
  echo "Error: $REPO_DIR does not exist. Clone the repo first:" >&2
  echo "  git clone <your-repo-url> $REPO_DIR" >&2
  exit 1
fi

cd "$REPO_DIR"
echo "→ Working directory: $(pwd)"
echo ""

echo "→ Updating code (git pull)..."
git pull
echo ""

echo "→ Setting executable permissions..."
chmod +x deploy/deploy.sh deploy/verify.sh
echo ""

# ── Helpers ───────────────────────────────────────────────────────────────────

env_line() {
  local key="$1"
  local val="$2"
  if [[ "$val" =~ [[:space:]#\"\$\\] ]]; then
    printf '%s="%s"\n' "$key" "$(printf '%s' "$val" | sed 's/"/\\"/g')"
  else
    printf '%s=%s\n' "$key" "$val"
  fi
}

prompt_required() {
  local name="$1"
  local label="$2"
  local secret="${3:-false}"
  local input=""

  if [[ "$secret" == "true" ]]; then
    read -rsp "$label: " input
    echo ""
  else
    read -rp "$label: " input
  fi

  if [[ -z "$input" ]]; then
    echo "Error: $name is required." >&2
    exit 1
  fi
  printf -v "$name" '%s' "$input"
}

# ── Environment configuration ─────────────────────────────────────────────────

echo "Enter values for deploy/.env.signal"
echo "(SUPABASE_URL = same value as NEXT_PUBLIC_SUPABASE_URL on Vercel)"
echo ""

prompt_required SUPABASE_URL "SUPABASE_URL"
prompt_required SUPABASE_SERVICE_ROLE_KEY "SUPABASE_SERVICE_ROLE_KEY" true
prompt_required UPSTASH_REDIS_REST_URL "UPSTASH_REDIS_REST_URL"
prompt_required UPSTASH_REDIS_REST_TOKEN "UPSTASH_REDIS_REST_TOKEN" true
prompt_required TELEGRAM_API_ID "TELEGRAM_API_ID"
prompt_required TELEGRAM_API_HASH "TELEGRAM_API_HASH" true
prompt_required TELEGRAM_SESSION_STRING "TELEGRAM_SESSION_STRING" true
prompt_required SIGNAL_WORKER_SECRET "SIGNAL_WORKER_SECRET" true

echo ""
echo "→ Writing $ENV_FILE ..."

umask 077
{
  echo "# Generated by deploy/deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "# NEVER commit this file."
  echo ""
  env_line UPSTASH_REDIS_REST_URL "$UPSTASH_REDIS_REST_URL"
  env_line UPSTASH_REDIS_REST_TOKEN "$UPSTASH_REDIS_REST_TOKEN"
  echo ""
  env_line SUPABASE_URL "$SUPABASE_URL"
  env_line SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
  echo ""
  env_line SIGNAL_ASSESS_URL "https://www.cryptocheckai.com"
  env_line SIGNAL_WORKER_SECRET "$SIGNAL_WORKER_SECRET"
  echo ""
  env_line SIGNAL_SOURCES "telegram"
  echo ""
  env_line TELEGRAM_API_ID "$TELEGRAM_API_ID"
  env_line TELEGRAM_API_HASH "$TELEGRAM_API_HASH"
  env_line TELEGRAM_SESSION_STRING "$TELEGRAM_SESSION_STRING"
  echo ""
  env_line SIGNAL_CHANNELS_CONFIG "services/ingestion/config/channels.json"
  env_line SIGNAL_SESSION_INDEX "0"
  env_line SIGNAL_SESSION_COUNT "1"
  env_line SIGNAL_INGESTION_HEALTH_PORT "4101"
  env_line SIGNAL_STREAM_UNIFIED_MAXLEN "100000"
  echo ""
  env_line SCOUT_ENABLED "true"
  env_line SCOUT_DRY_RUN "false"
  env_line SCOUT_MIN_REPUTATION "80"
  env_line SCOUT_MAX_INSERTS "25"
  env_line SCOUT_TELEGRAM_ENABLED "true"
  env_line SCOUT_MIN_SUBSCRIBERS "10000"
  env_line SCOUT_TELEGRAM_REQUIRE_VERIFICATION "true"
  env_line SCOUT_TWITTER_ENABLED "false"
  echo ""
  env_line SIGNAL_GATE_CONSUMER "gate-droplet-1"
  env_line SIGNAL_GATE_BATCH "10"
  env_line SIGNAL_GATE_BLOCK_MS "3000"
  env_line SIGNAL_GATE_HEALTH_PORT "4105"
  echo ""
  env_line SIGNAL_AGENT_ENABLED "false"
  env_line SIGNAL_AGENT_KILL_SWITCH "true"
  env_line SIGNAL_AGENT_MODE "paper"
  env_line SIGNAL_AGENT_SIGNING_KEY ""
  echo ""
  env_line PROOF_ENGINE_ENABLED "false"
  env_line PROOF_ENGINE_DRY_RUN "true"
  env_line PROOF_ENGINE_AUTO_POST "false"
} >"$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "   Done (mode 600)"
echo ""

# ── Execution ─────────────────────────────────────────────────────────────────

if ! command -v docker >/dev/null 2>&1; then
  echo "Error: docker not found. Install: curl -fsSL https://get.docker.com | sh" >&2
  exit 1
fi

echo "→ Starting Docker Compose (build + up)..."
docker compose -p "$COMPOSE_PROJECT" -f "$COMPOSE_FILE" up -d --build
echo ""

docker compose -p "$COMPOSE_PROJECT" -f "$COMPOSE_FILE" ps
echo ""

# ── Monitoring ────────────────────────────────────────────────────────────────

echo "=== Deploy complete ==="
echo ""
echo "Watch logs now:"
echo "  docker compose -p cryptocheck-signal -f deploy/docker-compose.signal.yml logs -f"
echo ""
echo "Verify after logs look healthy:"
echo "  ./deploy/verify.sh"
echo ""
echo "Expect:"
echo "  [signal-ingestion] Connected to Telegram"
echo "  [signal-ingestion] Monitoring N channels"
echo "  [signal-pipeline:gate] Gate consumer started"
