# Écrit le fichier via Python sans heredoc
python3 -c "
import os
lines = []
lines.append(\"'use client'\")
lines.append(\"import React, { useState, useEffect } from 'react'\")
lines.append(\"import { createClient } from '@supabase/supabase-js'\")
lines.append(\"import AuthModal from '../../components/AuthModal'\")
lines.append(\"\")
lines.append(\"const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!)\")
lines.append(\"const T = '#20b2aa'\")
lines.append(\"const IF = \\\"'Inter',sans-serif\\\"\")
lines.append(\"const MF = \\\"'JetBrains Mono',monospace\\\"\")
lines.append(\"\")
lines.append(\"export default function LandingPage() {\")
lines.append(\"  const [showAuth, setShowAuth] = useState(false)\")
lines.append(\"  const [user, setUser] = useState<any>(null)\")
lines.append(\"\")
lines.append(\"  useEffect(() => {\")
lines.append(\"    sb.auth.getSession().then(({ data }) => setUser(data.session?.user ?? null))\")
lines.append(\"    const { data: { subscription } } = sb.auth.onAuthStateChange((_e, s) => {\")
lines.append(\"      setUser(s?.user ?? null)\")
lines.append(\"      if (s?.user) window.location.replace('/app')\")
lines.append(\"    })\")
lines.append(\"    return () => subscription.unsubscribe()\")
lines.append(\"  }, [])\")
lines.append(\"\")
lines.append(\"  const go = () => user ? window.location.replace('/app') : setShowAuth(true)\")
lines.append(\"\")
lines.append(\"  return (\")
lines.append(\"    <div style={{ background: '#000', color: '#e2e8f0', fontFamily: IF, minHeight: '100vh', fontWeight: 300 }}>\")
lines.append(\"\")
lines.append(\"      <nav style={{ position: 'sticky', top: 0, zIndex: 100, height: 48, background: 'rgba(0,0,0,0.95)', borderBottom: '1px solid rgba(32,178,170,0.12)', display: 'flex', alignItems: 'center', padding: '0 28px', gap: 10 }}>\")
lines.append(\"        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>\")
lines.append(\"          <img src='/logo.jpg' alt='logo' style={{ width: 22, height: 22, borderRadius: 4, objectFit: 'cover' }} />\")
lines.append(\"          <span style={{ fontSize: 14, fontWeight: 700, color: '#fff', letterSpacing: '-0.02em', fontFamily: IF }}>\")
lines.append(\"            CryptoCheck<span style={{ color: T }}>AI</span>\")
lines.append(\"          </span>\")
lines.append(\"        </div>\")
lines.append(\"        <div style={{ display: 'flex', marginLeft: 20 }}>\")
lines.append(\"          {['Features', 'Pricing', 'Neural Scan', 'Whale Intel'].map(t => (\")
lines.append(\"            <a key={t} href='#' style={{ padding: '5px 14px', fontSize: 12, color: 'rgba(255,255,255,0.45)', fontWeight: 400, textDecoration: 'none', fontFamily: IF }}>{t}</a>\")
lines.append(\"          ))}\")
lines.append(\"        </div>\")
lines.append(\"        <div style={{ marginLeft: 'auto', display: 'flex', gap: 8, alignItems: 'center' }}>\")
lines.append(\"          <button onClick={go} style={{ padding: '5px 14px', fontSize: 12, color: 'rgba(255,255,255,0.45)', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 400, fontFamily: IF }}>{user ? 'Dashboard' : 'Sign In'}</button>\")
lines.append(\"          <button onClick={go} style={{ padding: '7px 18px', background: T, color: '#000', border: 'none', borderRadius: 4, fontSize: 12, fontWeight: 700, cursor: 'pointer', fontFamily: IF }}>Launch App</button>\")
lines.append(\"        </div>\")
lines.append(\"      </nav>\")
lines.append(\"\")
lines.append(\"      <section style={{ minHeight: '88vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '60px 24px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>\")
lines.append(\"        <div style={{ position: 'absolute', top: '10%', left: '15%', width: 400, height: 400, background: 'radial-gradient(circle,rgba(32,178,170,0.08) 0%,transparent 65%)', pointerEvents: 'none' }} />\")
lines.append(\"        <div style={{ position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(rgba(32,178,170,0.02) 1px,transparent 1px),linear-gradient(90deg,rgba(32,178,170,0.02) 1px,transparent 1px)', backgroundSize: '56px 56px', pointerEvents: 'none' }} />\")
lines.append(\"\")
lines.append(\"        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 7, padding: '4px 14px', background: 'rgba(32,178,170,0.08)', border: '1px solid rgba(32,178,170,0.18)', borderRadius: 20, fontSize: 10, color: T, marginBottom: 32, letterSpacing: '0.06em', fontFamily: MF }}>\")
lines.append(\"          <span style={{ width: 5, height: 5, borderRadius: '50%', background: T, display: 'inline-block' }} /> LIVE ON SOLANA MAINNET\")
lines.append(\"        </div>\")
lines.append(\"\")
lines.append(\"        <h1 style={{ fontSize: 'clamp(38px,6vw,72px)', fontWeight: 800, lineHeight: 1.03, letterSpacing: '-0.03em', maxWidth: 840, margin: '0 auto 20px', fontFamily: IF }}>\")
lines.append(\"          <span style={{ color: '#fff' }}>SCAN AND PROTECT</span><br />\")
lines.append(\"          <span style={{ color: T }}>SOLANA TOKENS</span><br />\")
lines.append(\"          <span style={{ color: '#fff' }}>AT LIGHTNING SPEED</span>\")
lines.append(\"        </h1>\")
lines.append(\"\")
lines.append(\"        <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.35)', maxWidth: 500, margin: '0 auto 36px', lineHeight: 1.8, fontWeight: 300, fontFamily: IF }}>\")
lines.append(\"          Neural AI · Rug Detection · Whale Tracking · Auto-Sniper\")
lines.append(\"        </p>\")
lines.append(\"\")
lines.append(\"        <div style={{ display: 'flex', gap: 10, justifyContent: 'center', marginBottom: 48 }}>\")
lines.append(\"          <button onClick={go} style={{ padding: '13px 30px', background: T, color: '#000', border: 'none', borderRadius: 5, fontSize: 13, fontWeight: 700, cursor: 'pointer', fontFamily: IF, boxShadow: '0 0 32px rgba(32,178,170,0.3)' }}>Launch App Free</button>\")
lines.append(\"          <a href='#features' style={{ padding: '13px 24px', background: 'rgba(32,178,170,0.06)', color: 'rgba(32,178,170,0.8)', border: '1px solid rgba(32,178,170,0.18)', borderRadius: 5, fontSize: 13, fontWeight: 400, textDecoration: 'none', fontFamily: IF }}>Documentation</a>\")
lines.append(\"        </div>\")
lines.append(\"\")
lines.append(\"        <div style={{ display: 'flex', marginBottom: 52, border: '1px solid rgba(32,178,170,0.12)', borderRadius: 5, overflow: 'hidden' }}>\")
lines.append(\"          {[['4.2M+', 'PROTECTED'], ['14902', 'SCANNED'], ['97%', 'ACCURACY'], ['200ms', 'RESPONSE']].map(([v, l]) => (\")
lines.append(\"            <div key={l} style={{ padding: '12px 24px', borderRight: '1px solid rgba(32,178,170,0.08)', textAlign: 'center' }}>\")
lines.append(\"              <div style={{ fontSize: 20, fontWeight: 700, color: T, fontFamily: MF }}>{v}</div>\")
lines.append(\"              <div style={{ fontSize: 9, color: 'rgba(32,178,170,0.3)', marginTop: 4, letterSpacing: '0.1em', fontFamily: MF }}>{l}</div>\")
lines.append(\"            </div>\")
lines.append(\"          ))}\")
lines.append(\"        </div>\")
lines.append(\"      </section>\")
lines.append(\"\")
lines.append(\"      <section id='features' style={{ padding: '72px 24px', maxWidth: 960, margin: '0 auto' }}>\")
lines.append(\"        <div style={{ textAlign: 'center', marginBottom: 48 }}>\")
lines.append(\"          <div style={{ fontSize: 10, fontWeight: 500, letterSpacing: '0.12em', color: T, marginBottom: 12, fontFamily: MF }}>WHY CRYPTOCHECK AI</div>\")
lines.append(\"          <h2 style={{ fontSize: 'clamp(24px,4vw,42px)', fontWeight: 800, color: '#fff', letterSpacing: '-0.02em', fontFamily: IF }}>Professional tools for<br /><span style={{ color: T }}>serious Solana traders</span></h2>\")
lines.append(\"        </div>\")
lines.append(\"        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', border: '1px solid rgba(32,178,170,0.08)', borderRadius: 6, overflow: 'hidden' }}>\")
lines.append(\"          {[\")
lines.append(\"            { icon: '🧠', t: 'Neural Scan V4', b: 'FREE', pro: false, d: 'AI risk scoring and holder distribution in under 2s.' },\")
lines.append(\"            { icon: '⚡', t: 'AI Prediction', b: 'PRO', pro: true, d: '5m-15m predictions using whale patterns.' },\")
lines.append(\"            { icon: '🐋', t: 'Whale Intel', b: 'PRO', pro: true, d: 'Track smart money before the pump.' },\")
lines.append(\"            { icon: '🔐', t: 'Rug Forensics', b: 'PRO', pro: true, d: 'Deep contract analysis and bundling detection.' },\")
lines.append(\"            { icon: '🎯', t: 'Auto-Sniper', b: 'PRO', pro: true, d: 'AI executes trades on high-probability setups.' },\")
lines.append(\"            { icon: '📡', t: 'Alpha Feed', b: 'PRO', pro: true, d: 'Real-time whale alerts and new pools.' },\")
lines.append(\"          ].map((f, i) => (\")
lines.append(\"            <div key={f.t} style={{ background: '#000', padding: '20px', borderRight: i % 3 !== 2 ? '1px solid rgba(32,178,170,0.06)' : 'none', borderBottom: i < 3 ? '1px solid rgba(32,178,170,0.06)' : 'none' }}\")
lines.append(\"              onMouseEnter={e => (e.currentTarget.style.background = 'rgba(32,178,170,0.02)')}\")
lines.append(\"              onMouseLeave={e => (e.currentTarget.style.background = '#000')}>\")
lines.append(\"              <div style={{ fontSize: 18, marginBottom: 8 }}>{f.icon}</div>\")
lines.append(\"              <div style={{ fontSize: 13, fontWeight: 600, color: '#e2e8f0', marginBottom: 4, fontFamily: IF }}>{f.t}</div>\")
lines.append(\"              <span style={{ fontSize: 8, padding: '2px 7px', borderRadius: 2, background: f.pro ? 'rgba(245,158,11,0.08)' : 'rgba(32,178,170,0.08)', color: f.pro ? '#f59e0b' : T, border: '1px solid rgba(32,178,170,0.18)', display: 'inline-block', marginBottom: 8, fontFamily: MF }}>{f.b}</span>\")
lines.append(\"              <p style={{ fontSize: 11, color: 'rgba(32,178,170,0.4)', lineHeight: 1.7, fontWeight: 300, margin: 0, fontFamily: IF }}>{f.d}</p>\")
lines.append(\"            </div>\")
lines.append(\"          ))}\")
lines.append(\"        </div>\")
lines.append(\"      </section>\")
lines.append(\"\")
lines.append(\"      <section id='pricing' style={{ padding: '64px 24px', maxWidth: 760, margin: '0 auto' }}>\")
lines.append(\"        <div style={{ textAlign: 'center', marginBottom: 40 }}>\")
lines.append(\"          <div style={{ fontSize: 10, fontWeight: 500, letterSpacing: '0.12em', color: T, marginBottom: 12, fontFamily: MF }}>PRICING</div>\")
lines.append(\"          <h2 style={{ fontSize: 'clamp(22px,3.5vw,36px)', fontWeight: 800, color: '#fff', letterSpacing: '-0.02em', fontFamily: IF }}>Simple, transparent pricing</h2>\")
lines.append(\"        </div>\")
lines.append(\"        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', border: '1px solid rgba(32,178,170,0.08)', borderRadius: 6, overflow: 'hidden' }}>\")
lines.append(\"          {[\")
lines.append(\"            { n: 'STARTER', p: '5', per: 'one-time', pop: false, f: ['10 Neural Scans', 'Rug Detection', '30 days'], cta: 'Get Started' },\")
lines.append(\"            { n: 'PRO', p: '30', per: '/month', pop: true, f: ['Unlimited Credits', 'AI Predictions', 'Auto-Sniper', 'Whale Tracking'], cta: 'Upgrade to Pro' },\")
lines.append(\"            { n: 'WHALE', p: 'FREE', per: '0.5% fee', pop: false, f: ['Everything in Pro', '0.5% profits only', 'VIP Telegram'], cta: 'Apply for Whale' },\")
lines.append(\"          ].map((pl, i) => (\")
lines.append(\"            <div key={pl.n} style={{ background: pl.pop ? '#050505' : '#000', padding: '22px', borderRight: i < 2 ? '1px solid rgba(32,178,170,0.08)' : 'none', position: 'relative', overflow: 'hidden' }}>\")
lines.append(\"              {pl.pop && <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 1, background: 'linear-gradient(90deg,transparent,#20b2aa,transparent)' }} />}\")
lines.append(\"              {pl.pop && <div style={{ fontSize: 8, fontWeight: 700, color: '#000', background: T, padding: '2px 8px', borderRadius: 2, display: 'inline-block', marginBottom: 8, fontFamily: MF }}>MOST POPULAR</div>}\")
lines.append(\"              <div style={{ fontSize: 10, fontWeight: 500, color: 'rgba(32,178,170,0.5)', marginBottom: 6, letterSpacing: '0.1em', fontFamily: MF }}>{pl.n}</div>\")
lines.append(\"              <div style={{ fontSize: 28, fontWeight: 700, color: T, lineHeight: 1, marginBottom: 2, fontFamily: MF }}>{pl.p === 'FREE' ? 'FREE' : '$' + pl.p}</div>\")
lines.append(\"              <div style={{ fontSize: 10, color: 'rgba(32,178,170,0.25)', marginBottom: 16, fontWeight: 300 }}>{pl.per}</div>\")
lines.append(\"              <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 16 }}>\")
lines.append(\"                {pl.f.map(feat => (<div key={feat} style={{ fontSize: 11, color: 'rgba(32,178,170,0.5)', display: 'flex', gap: 7, fontWeight: 300, fontFamily: IF }}><span style={{ color: T }}>✓</span>{feat}</div>))}\")
lines.append(\"              </div>\")
lines.append(\"              <button onClick={go} style={{ width: '100%', padding: '8px', background: pl.pop ? T : 'rgba(32,178,170,0.06)', border: pl.pop ? 'none' : '1px solid rgba(32,178,170,0.18)', borderRadius: 3, color: pl.pop ? '#000' : T, fontSize: 11, fontWeight: pl.pop ? 700 : 400, cursor: 'pointer', fontFamily: IF }}>{pl.cta}</button>\")
lines.append(\"            </div>\")
lines.append(\"          ))}\")
lines.append(\"        </div>\")
lines.append(\"      </section>\")
lines.append(\"\")
lines.append(\"      <section style={{ padding: '64px 24px', textAlign: 'center', position: 'relative' }}>\")
lines.append(\"        <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse at center,rgba(32,178,170,0.05) 0%,transparent 60%)', pointerEvents: 'none' }} />\")
lines.append(\"        <h2 style={{ fontSize: 'clamp(24px,4vw,40px)', fontWeight: 800, color: '#fff', marginBottom: 12, letterSpacing: '-0.02em', fontFamily: IF, position: 'relative' }}>\")
lines.append(\"          START PROTECTING YOUR<br /><span style={{ color: T }}>SOLANA PORTFOLIO TODAY</span>\")
lines.append(\"        </h2>\")
lines.append(\"        <p style={{ fontSize: 11, color: 'rgba(32,178,170,0.3)', marginBottom: 24, letterSpacing: '0.08em', fontWeight: 300, fontFamily: MF, position: 'relative' }}>10 FREE SCANS - NO CREDIT CARD</p>\")
lines.append(\"        <button onClick={go} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '13px 30px', background: T, color: '#000', border: 'none', borderRadius: 5, fontSize: 13, fontWeight: 700, cursor: 'pointer', fontFamily: IF, position: 'relative' }}>Launch App Free</button>\")
lines.append(\"      </section>\")
lines.append(\"\")
lines.append(\"      <footer style={{ borderTop: '1px solid rgba(32,178,170,0.07)', padding: '18px 28px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10, background: '#050505' }}>\")
lines.append(\"        <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>\")
lines.append(\"          <img src='/logo.jpg' alt='logo' style={{ width: 18, height: 18, borderRadius: 3, objectFit: 'cover' }} />\")
lines.append(\"          <span style={{ fontSize: 12, fontWeight: 600, color: '#e2e8f0', fontFamily: IF }}>CryptoCheck AI</span>\")
lines.append(\"          <span style={{ fontSize: 9, color: 'rgba(32,178,170,0.2)', fontWeight: 300 }}>2026</span>\")
lines.append(\"        </div>\")
lines.append(\"        <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>\")
lines.append(\"          <span style={{ width: 5, height: 5, borderRadius: '50%', background: T }} />\")
lines.append(\"          <span style={{ fontSize: 9, color: T, letterSpacing: '0.08em', fontFamily: MF }}>LIVE - SOLANA MAINNET</span>\")
lines.append(\"        </div>\")
lines.append(\"        <div style={{ display: 'flex', gap: 16 }}>\")
lines.append(\"          {['Privacy', 'Terms', 'Docs', 'Contact'].map(l => (\")
lines.append(\"            <a key={l} href='#' style={{ fontSize: 10, color: 'rgba(32,178,170,0.25)', fontWeight: 300, textDecoration: 'none', fontFamily: IF }}>{l}</a>\")
lines.append(\"          ))}\")
lines.append(\"        </div>\")
lines.append(\"      </footer>\")
lines.append(\"\")
lines.append(\"      {showAuth && <AuthModal onClose={() => setShowAuth(false)} onSuccess={(u: any) => { setUser(u); window.location.replace('/app') }} />}\")
lines.append(\"    </div>\")
lines.append(\"  )\")
lines.append(\"}\")

with open('./app/landing/page.tsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('Done:', len(lines), 'lines')
"